runtime: nodejs20
env: standard

# Build the application before deployment
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Environment variables (configure these in Google Cloud Console or via gcloud CLI)
env_variables:
  NODE_ENV: "production"
  # GEMINI_API_KEY: "your-api-key-here"  # Set this via: gcloud app deploy --set-env-vars GEMINI_API_KEY=your-key

handlers:
  # Melayani file statis (Assets)
  - url: /assets
    static_dir: dist/assets
    secure: always
    redirect_http_response_code: 301

  # Melayani file statis root (favicon, dll)
  - url: /(.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot)$
    secure: always
    redirect_http_response_code: 301

  # Catch-all untuk SPA Routing
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301
